apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: stable
    spec:
      containers:
        - name: api-gateway
          image: lkusmierczyk/api-gateway:1.4-snap
          ports:
          - containerPort: 8083
          envFrom:
            - configMapRef:
                name: api-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment-risky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: risky
    spec:
      containers:
        - name: api-gateway
          image: lkusmierczyk/api-gateway:1.3-snap
          ports:
          - containerPort: 8083
          envFrom:
            - configMapRef:
                name: api-gateway
