apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer.fullName" . }}-service
spec:
  selector:
    app: {{ include "customer.fullName" . }}
  ports:
    - port: 8081
      targetPort: 8081
  type: {{ .Values.service.type }}
