apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer.fullName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "customer.fullName" . }}
  template:
    metadata:
      labels:
        app: {{ include "customer.fullName" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "customer.fullName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 8081
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "customer.fullName" . }}-secret
                key: DB_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "customer.fullName" . }}-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "customer.fullName" . }}-secret
                key: DB_PASSWORD
