replicaCount: 2

image:
  pullPolicy: Always
  repository: lkusmierczyk/customer-service
  tag: "1.7-snap"

service:
  type: ClusterIP
  port: 8081

database:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdzcWwtcG9zdGdyZXNxbC5zaG9wLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZGJfY3VzdG9tZXI=
  user: dV9jdXN0b21lcg==
  password: Y3VzdG9tZXI=
